"""add stock chart cache tables

Revision ID: 142b5054ff72
Revises: 27931fa8f7af
Create Date: 2026-03-09 20:43:38.710234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142b5054ff72'
down_revision = '27931fa8f7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_chart_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'datetime', name='uq_chart_symbol_interval_dt')
    )
    with op.batch_alter_table('stock_chart_candles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_chart_candles_symbol'), ['symbol'], unique=False)

    op.create_table('stock_chart_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('candle_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', name='uq_chart_meta_symbol_interval')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_chart_meta')
    with op.batch_alter_table('stock_chart_candles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_chart_candles_symbol'))

    op.drop_table('stock_chart_candles')
    # ### end Alembic commands ###
