"""add kyc status fields to users

Revision ID: 27931fa8f7af
Revises: 9a4ac4d995bc
Create Date: 2026-03-04 18:01:17.429125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27931fa8f7af'
down_revision = '9a4ac4d995bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_status', sa.String(length=20), server_default='unverified', nullable=False))
        batch_op.add_column(sa.Column('kyc_submitted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('kyc_rejection_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('kyc_rejection_reason')
        batch_op.drop_column('kyc_verified_at')
        batch_op.drop_column('kyc_submitted_at')
        batch_op.drop_column('kyc_status')

    # ### end Alembic commands ###
