"""Add transaction id to withdrawal model

Revision ID: 75f2f149fd44
Revises: 88a582ac9387
Create Date: 2026-04-06 08:56:01.122175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f2f149fd44'
down_revision = '88a582ac9387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_withdrawal_requests_transaction_id',
            'transactions', ['transaction_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_withdrawal_requests_transaction_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_transaction_id'))
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
