"""Add withdrawal_requests table

Revision ID: 9a4ac4d995bc
Revises: 4201a4c74631
Create Date: 2026-02-28 16:26:02.111092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4ac4d995bc'
down_revision = '4201a4c74631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('crypto_address', sa.String(length=255), nullable=False),
    sa.Column('crypto_currency', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('actioned_by', sa.Integer(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actioned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.create_index('idx_withdrawal_status', ['status'], unique=False)
        batch_op.create_index('idx_withdrawal_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_withdrawal_user_id')
        batch_op.drop_index('idx_withdrawal_status')

    op.drop_table('withdrawal_requests')
    # ### end Alembic commands ###
